install.package("dplyr")
install.packages("dplyr")
library(dplyr)
sessionInfo()
dplyr
tibble
mtcars
mtcars> head()
mtcars %>% head()
dim()
also : dim()
mtcars %>% dim()
mtcars %>% nrow()
mtcars %>% ncol()
mtcars %>% names()
mtcars %>% class()
mtcars %>% summary()
iris %>% summary()
iris %>% glompse
iris %>% glimpse
iris2 <- iris%>% filter()
filter(iris, Species=="Setosa")
iris2 <- iris%>% filter(Species== "Setosa")
iris2 %>% dim()
iris3 <- iris %>% filter(Sepal.Length.2)
iris3 <- iris %>% filter(Sepal.Length>2)
iris3 %>% dim()
iris3 %>% iris %>% filter(Sepal.Length>5)
iris3 <- iris %>% filter(Sepal.Length>5)
iris3 <- iris %>% filter(Sepal.Length>5)
iris3 <- iris %>% filter(Sepal.Length>2)
iris
iris3 <- iris %>% filter(Sepal.Length>2)
iris3 <- iris %>% filter(Sepal.Length>2)
iris3 <- iris %>% filter(Sepal.Length>2)
iris3 <- iris %>% filter(Sepal.Length>5)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length>5.2)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length>5.4)
iris3 %>% dim()
iris3 <- iris %>% filter(Sepal.Length>5.6)
iris3 %>% dim()
history(50)

